library(tidyverse)
library(rJava)
library(rcdk)
library(fingerprint)
library(webchem)

options(java.parameters = "-Xmx64g") # needed for windows

bcfData <- read.csv("bcfData.csv", check.names = FALSE)
fpIndex <- read.csv("fpIndex.csv", check.names = FALSE)
mols <- parse.smiles(distinct(bcfData, SMILES)[[1]])

# Un0 - Un54 fingerprints in SIRIUS custom

smarts1 <- as.character(fpIndex$smarts[fpIndex$fpType == "custom1"])
colnames1 <- as.character(fpIndex$fpName[fpIndex$fpType == "custom1"])

custom.fp1 <- lapply(mols, get.fingerprint, type = "substructure", substructure.pattern = smarts1)
custom.fp1 <- fp.to.matrix(custom.fp1)
colnames(custom.fp1) <- colnames1

# CDK (default) fingerprints

substructure <- lapply(mols, get.fingerprint, type = "substructure")
substructure <- fp.to.matrix(substructure)
colnames(substructure) <- paste0("Un", seq(55, 54 + ncol(substructure)))
substructure_filter <- as.integer(fpIndex$typeIndex[fpIndex$fpType == "substructure"])
substructure <- substructure[,substructure_filter]

# MACCS

maccs <- lapply(mols, get.fingerprint, type = "maccs")
maccs <- fp.to.matrix(maccs)
colnames(maccs) <- paste0("Un", seq(362, 361 + ncol(maccs)))
maccs_filter <- as.integer(fpIndex$typeIndex[fpIndex$fpType == "maccs"])
maccs <- maccs[,maccs_filter]

# PubChem CACTVS

# for (i in 1:length(mols)) {
# 
#   j <- lapply(mols[i], get.fingerprint, type = "pubchem")
# 
#   if (i == 1) {
#     cactvs <- j
#   } else cactvs <- append(cactvs, j)
# 
#   rJava::.jgc(R.gc = TRUE)
#   rJava::.jclear()
#   rJava::.jcheck()
# 
# } # serious Java issues with larger sets

# if failed due to Java error, mols object can be corrupted and needs to be reinitialised

cactvs <- lapply(mols, get.fingerprint, type = "pubchem")
cactvs <- fp.to.matrix(cactvs)
colnames(cactvs) <- paste0("Un", seq(528, 527 + ncol(cactvs)))
cactvs_filter <- as.integer(fpIndex$typeIndex[fpIndex$fpType == "cactvs"])
cactvs <- cactvs[,cactvs_filter]

# Klekota-Roth

# for (i in 1:length(mols)) {
# 
#   j <- lapply(mols[i], get.fingerprint, type = "kr")
# 
#   if (i == 1) {
#     kroth <- j
#   } else kroth <- append(kroth, j)
# 
#   rJava::.jgc(R.gc = TRUE)
#   rJava::.jclear()
#   rJava::.jcheck()
# 
# } # serious Java issues with larger sets

kroth <- lapply(mols, get.fingerprint, type = "kr")
kroth <- fp.to.matrix(kroth)
colnames(kroth) <- paste0("Un", seq(1409, 1408 + ncol(kroth)))
kroth_filter <- as.integer(fpIndex$typeIndex[fpIndex$fpType == "kroth"])
kroth <- kroth[,kroth_filter]

# ECFP6

# ecfp6 <- lapply(mols, get.fingerprint, type = "circular", fp.mode = "raw")
# ecfp6 <- fp.to.matrix(ecfp6)
# colnames(ecfp6) <- paste0("Un", seq(6269, 6268 + ncol(ecfp6)))
# ecfp6_filter <- as.integer(fpIndex$typeIndex[fpIndex$fpType == "ecfp6"]) # more than are generated by rcdk
# ecfp6 <- ecfp6[,ecfp6_filter]

# Custom Fingerprints 2

smarts2 <- as.character(fpIndex$smarts[fpIndex$fpType == "custom2"])
colnames2 <- as.character(fpIndex$fpName[fpIndex$fpType == "custom2"])

# for (i in 1:length(mols)) {
# 
#   j <- lapply(mols[i], get.fingerprint, type = "substructure", substructure.pattern = smarts2)
# 
#   if (i == 1) {
#     custom.fp2 <- j
#   } else custom.fp2 <- append(custom.fp2, j)
# 
#   rJava::.jgc(R.gc = TRUE)
#   rJava::.jclear()
#   rJava::.jcheck()
# 
# } # serious Java issues with larger sets

custom.fp2 <- lapply(mols, get.fingerprint, type = "substructure", substructure.pattern = smarts2)
custom.fp2 <- fp.to.matrix(custom.fp2)
colnames(custom.fp2) <- colnames2

# build model data

data <- bcfData %>%
  distinct(SMILES) %>%
  bind_cols(custom.fp1) %>%
  bind_cols(substructure) %>%
  bind_cols(maccs) %>%
  bind_cols(cactvs) %>%
  bind_cols(kroth) %>%
  #bind_cols(ecfp6) %>%
  bind_cols(custom.fp2)

pc_data <- bcfData %>%
  distinct(SMILES, .keep_all = TRUE) %>%
  select(PubChem_CID, SMILES)

write.csv(data, "fpData.csv")

bcfModelData <- bcfData %>%
  select(species, log_bcf, PubChem_CID, SMILES) %>%
  left_join(data, by = "SMILES")

write.csv(bcfModelData, "bcfModelData.csv", row.names = FALSE)

save.image("descriptors.RData")
